spring:
  application:
    name: "ConfigServer"
  profiles:
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "file:////C://Users//dines//Documents//config"
        git:
          uri: "https://github.com/Dinesh1631/configServer.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

#Acutrator end points exposure
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "DineshYadavGolla"
server:
  port: 8071

##Rabbit mq connection details:
#rabbitmq:
#  host: "localhost"
#  port: 5672
#  username: "guest"
#  password: "guest"

  
 


