services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    extends:
      file: common-config.yml
      service: network-deploy-service

  ConfigServer:
    image: dineshhacker/config:v12
    container_name: configServer-ms
    ports:
      - 8071:8071
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 5
      timeout: 10s
      start_interval: 10s
    extends:
      file: common-config.yml
      service: base_microService_config

  eurekaserver:
    image: dineshhacker/eureka:v12
    container_name: eureka-ms
    ports:
      - 8070:8070
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 5
      timeout: 10s
      start_interval: 10s
    extends:
      file: common-config.yml
      service: microservice_configServer_config
    depends_on:
      ConfigServer:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  Accounts:
    image: dineshhacker/account:v12
    container_name: account-ms
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 10s
      start_interval: 30s
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice_eureka_config
    environment:
      SPRING_APPLICATION_NAME: "accounts"

  cards:
    image: dineshhacker/cards:v12
    container_name: cards-ms
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 10s
      start_interval: 30s
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice_eureka_config
    environment:
      SPRING_APPLICATION_NAME: "cards"

  loans:
    image: dineshhacker/loans:v12
    container_name: loan-ms
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 10s
      start_interval: 30s
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice_eureka_config
    environment:
      SPRING_APPLICATION_NAME: "loans"

  GatewayServer:
    image: dineshhacker/gatewayserver:v12
    container_name: GatewayServer-ms
    ports:
      - 8072:8072
    depends_on:
      Accounts:
        condition: service_healthy
      cards:
        condition: service_healthy  
      loans:
        condition: service_healthy 
    extends:
      file: common-config.yml
      service: microservice_eureka_config
    environment:
      SPRING_APPLICATION_NAME: "GatewayServer" 
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"      

networks:
  dineshbank:
    driver: bridge
